# Generated by Django 5.1.7 on 2025-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField()),
                ('platform', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('screen_width', models.IntegerField()),
                ('screen_height', models.IntegerField()),
                ('timezone', models.CharField(max_length=100)),
                ('online', models.BooleanField()),
                ('cookies_enabled', models.BooleanField()),
                ('touch_support', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
