# Generated by Django 5.1.7 on 2025-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_deviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField()),
                ('platform', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('browser_name', models.CharField(max_length=100)),
                ('browser_version', models.CharField(max_length=50)),
                ('device_memory', models.CharField(blank=True, max_length=10, null=True)),
                ('hardware_concurrency', models.CharField(blank=True, max_length=10, null=True)),
                ('battery_level', models.CharField(blank=True, max_length=10, null=True)),
                ('charging', models.BooleanField(blank=True, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('do_not_track', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
