# Generated by Django 5.1.7 on 2025-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_screenshot_visitorinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorinfo',
            name='battery_level',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='browser_name',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='charging',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='device_memory',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='do_not_track',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='hardware_concurrency',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='platform',
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='cookies_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='is_new_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='screen_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='timezone_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
