# Generated by Django 5.1.7 on 2025-05-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_visitorinfo_battery_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorinfo',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='screen_info',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='color_depth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='screen_height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='screen_width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='device_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='fingerprint',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='language',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='operating_system',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='timezone_offset',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
